### ISSUE TITLE
java.lang.VerifyError: com/fasterxml/jackson/dataformat/xml/XmlFactory

### ISSUE THREAD

**Issue by thewhitewood** [FasterXML/jackson-dataformat-xml#116]
Getting a VerifyError when using the following in AndroidStudio

```
compile 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.3.3@jar'
compile 'com.fasterxml.jackson.core:jackson-core:2.3.1@jar'
compile 'com.fasterxml.jackson.core:jackson-databind:2.3.3@jar'
compile 'com.fasterxml.jackson.core:jackson-annotations:2.3.0@jar'
```
even reverting to 
```
compile 'com.fasterxml.jackson.core:jackson-databind:2.1.2@jar'
compile 'com.fasterxml.jackson.core:jackson-annotations:2.1.1@jar'
compile 'com.fasterxml.jackson.core:jackson-core:2.1.1@jar'
compile 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.1.0@jar'
```
is causing errors - any ideas or is it a clash with a 3rd party library?

**Comment by cowtowncoder** [comment]
I can not reproduce this problem unfortunately. If there is specific fix to make, please reopen (or re-file) with specific request.

**Comment by xpmich** [comment]
Hi.
I have actually the same problem with the version 2.5.0 of jackson.
So, my build.gradle 
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 19
    buildToolsVersion '21.1.2'
    defaultConfig {
        applicationId "com.me.myapp"
        minSdkVersion 19
        targetSdkVersion 19
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/services/com.fasterxml.jackson.core.ObjectCodec'
        exclude 'META-INF/services/com.fasterxml.jackson.core.JsonFactory'
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile files('libs/jackson/jackson-annotations-2.5.0.jar')
    compile files('libs/jackson/jackson-core-2.5.0.jar')
    compile files('libs/jackson/jackson-dataformat-xml-2.5.0.jar')
    compile files('libs/jackson/jackson-databind-2.5.0.jar')
}
```
To generate a JSON file, no problem with this 
```
				objectMapper = new ObjectMapper();
				objectMapper.writeValue(jsonFileJackson, scoreboard);
```
To generate a XML file,
```
			XmlMapper mapper = new XmlMapper();
			String str = mapper.writeValueAsString(myObject );
```
I had exactely the same error 
```
    java.lang.VerifyError: com/fasterxml/jackson/dataformat/xml/XmlFactory
            at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:44)
```

**Comment by cowtowncoder** [comment]
Could it be that proguard is excluding something, causing this?

Also: does the same happen with 2.5.1?

**Comment by cowtowncoder** [comment]
Looking at code, this line is:

        this(new XmlFactory());

which eventually results in an attempt to construct an `XMLInputFactory` and `XMLOutputFactory` instances. I guess there are couple of things that could go wrong:

1. Inability to construct `XMLInputFactory` and/or `XMLOutputFactory`. This could be due to Android's issues with whitelisting `javax.` packages (Google for some reason uses incomplete list of available packages, and throws an error for attempts to load anything else -- that is, it's a bug)
2. Since construction of factories uses indirection, perhaps Proguard is pruning out components that are needed. In case of Woodstox, you would want to include `com.ctxt.wstx.stax.WstxInputFactory` and `com.ctc.wstx.stax.WstxOutputFactory`.

To avoid (2), it may make sense to explicitly construct and pass these factories, instead of relying JDK auto-discovery. So use something like:

```java
XmlFactory f = new XmlFactory(new WstxInputFactory(), new WstxOutputFactory());
XmlMapper mapper = new XmlMapper(f);
```

and this should help in either making things work, or showing more accurately what is failing.

**Comment by xpmich** [comment]
>Could it be that proguard is excluding something, causing this?

No, i'm not using proguard (not yet). it's the default file.

>Also: does the same happen with 2.5.1?

unfortunately 2.5.1 is'nt on the download page : 2.5.0 is the latest (download section)
[jackson-annotations](https://github.com/FasterXML/jackson-annotations/wiki)
[jackson-core](https://github.com/FasterXML/jackson-core/wiki)
[jackson-databind](https://github.com/FasterXML/jackson-databind/wiki)

I have tired the other way : add [woodstox](http://wiki.fasterxml.com/WoodstoxDownload) and add : 
[woodstox-core-asl-4.2.0.jar (AL 2.0)](http://repo1.maven.org/maven2/org/codehaus/woodstox/woodstox-core-asl/4.2.0/woodstox-core-asl-4.2.0.jar)
[woodstox-core-lgpl-4.2.0.jar (LGPL 2.1)](http://repo1.maven.org/maven2/org/codehaus/woodstox/woodstox-core-lgpl/4.2.0/woodstox-core-lgpl-4.2.0.jar)
[stax2-api-3.1.1 jar](http://repository.codehaus.org/org/codehaus/woodstox/stax2-api/3.1.1/stax2-api-3.1.1.jar)
I had this : 
```
import com.ctc.wstx.stax.WstxInputFactory;
import com.ctc.wstx.stax.WstxOutputFactory;
import com.fasterxml.jackson.dataformat.xml.XmlFactory;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
...
			XmlFactory f = new XmlFactory(new WstxInputFactory(), new WstxOutputFactory());
			XmlMapper mapper = new XmlMapper(f);
```
 error : 
```
Error:(54, 19) error: cannot access XMLInputFactory
class file for javax.xml.stream.XMLInputFactory not found
```
I had that you said : the bug with javax. I have tried to change my proguard-rules.pro file but i don't know how.
Can you explain to me ?

**Comment by cowtowncoder** [comment]
Ok. This may just be due to missing dependency to Stax API jar. It is part of Java6, which is why dependency is added as `provided` (that is, Maven is aware of it, but it is not added as transitive dependency for building). But Android SDK might not have it.
So instead of this in pom:

    <dependency>
      <groupId>javax.xml.stream</groupId>
      <artifactId>stax-api</artifactId>
      <version>1.0-2</version>
      <scope>provided</scope>
    </dependency>

you may need to add dependency in your build file, but with

      <scope>compile</scope>

and ensure that jar is included; via Maven it would be found from:

http://repo1.maven.org/maven2/javax/xml/stream/stax-api/1.0-2/

**Comment by xpmich** [comment]
It's not as easy.
I don't wanna use android XML wrapper because it's too intrusive (add implement serializable or @ param...) and with Jackson you have to add lots of dependence.

When i use jackson lib, I don'd have to do this but it's in JSON.

Nevermind, I keep jackson and work only with JSON (maybe later...)
As told Nilzor deservedly
>Apparently getting JAXB to work with Android is not trivial. User Sean Berbeau has a suggestion by using some rewritten Stax-libraries in this answser, but I haven't got it working:
>
>http://stackoverflow.com/questions/5461127/using-jaxb-with-google-android

thank you anyway.

**Comment by cowtowncoder** [comment]
Hmmh? All I suggested was that the API jar may be missing -- on JavaSE platforms it would be part of JDK; on Android maybe not (Oracle has chosen to do somewhat arbitrary subsets, so I honestly do not know if or if not the include it). This could solve your issue without other problems; Sean's notes may or may not apply, depending on version of Android SDK.

So it's addition of a single jar which Android SDK seems to be missing, from here:

http://repo1.maven.org/maven2/javax/xml/stream/stax-api/1.0-2/

and that is all.

Of course leaving out XML handling may be the simplest option. But I would like to know if this is the problem, and if so, others would find the it. Addition of dependency for Jackson XML module is possible, but it'd be sub-optimal for non-Android usage. So I'll have to think about that.

**Comment by xpmich** [comment]
Ok,
For this problem (Jackson XML on Android), If you create another issue (this one is closed!), please, leave the link, I wanna to follow it.

Thank.

**Comment by cowtowncoder** [comment]
I don't see any open issue here basically. To me this seems like inclusion that users on Android need to add: I will add a note on README stating this.
