### ISSUE TITLE
Missing newline after XML header

### ISSUE THREAD

**Issue by Poorman65** [FasterXML/jackson-dataformat-xml#131]
When the xml header is included with the xml serialization then there is not a newline between the end of the header and the xml content. Here is a very simple example:

```
<?xml version='1.1' encoding='UTF-8'?><MyPOJO>
  <value>TestValue</value>
  <valnum>246</valnum>
</MyPOJO>
```
```
File resultFile = new File("/home/oracle/test.xml");
XmlMapper mapper = new XmlMapper();
mapper.configure(SerializationFeature.INDENT_OUTPUT, true);
mapper.configure(ToXmlGenerator.Feature.WRITE_XML_1_1, true);
mapper.writeValue(resultFile, new MyPOJO());
```

Tested with Jackson 2.4.3 and woodstox-core-asl 4.4.1

**Comment by cowtowncoder** [comment]
This is not a bug, since output as shown is valid XML.
But I can consider it as a request for enhancement.

Underlying problem here is that XML writers generally do not expose this aspect for configuration (or not via standard API), since white space usage (or lack thereof) is semantically insignificant. Unlike white space within XML content itself, this white space is never reported to calling code.
So there may be practical difficulties in trying to get linefeed added.

**Comment by cowtowncoder** [comment]
Actually this should now work with 2.7.0(-rc2), as per #172.
