### ISSUE TITLE
All FromXmlParser numeric accessors return null or 0

### ISSUE THREAD

**Issue by dgaffuri** [FasterXML/jackson-dataformat-xml#145]
I've the following code in a custom deserializer to manage Oracle timestamps with nanoseconds:

    public Timestamp deserialize(final JsonParser jp, final DeserializationContext ctxt) throws IOException, JsonProcessingException {
	
        // get time and nanos, including milliseconds from time
        BigDecimal deserialized = jp.getDecimalValue();
that works with json but fails with a NPE when deserializing from xml.

**Comment by cowtowncoder** [comment]
The problem is fundamentally caused by problem with XML content: there is no format-level distinction between Strings and numbers, because all content is fundamentally textual. Because of this, xml-backed parser reports all content as VALUE_STRING. Databind can do proper coercions when it expects a number.
`JsonParser.getDecimalValue()`, however, specifically expects numeric token, so it will not work here.
There are alternative methods ("getValueAsInt()", "getValueAsDouble()") for some numeric types, but not for `BigDecimal` or `BigInteger`.
So you probably need to use `parser.getValueAsString()` and then construct `BigDecimal` with it.

I can try to see if error messaging can be improved as it definitely should not throw an NPE. But it should throw a more meaningful exception.

**Comment by dgaffuri** [comment]
Thanks for your prompt answer, it was exactly what i did:

    String deserializedString = jp.getValueAsString();
    BigDecimal deserialized;
    try {
        deserialized = new BigDecimal(deserializedString);
    } catch (NumberFormatException e) {
        throw new JsonParseException("error deserializing Timestamp", jp.getCurrentLocation(), e);
    }

Just a suggestion, may be it would be better to implement such kind of conversions in parser itself, throwing specific exceptions on failure.

**Comment by cowtowncoder** [comment]
@dgaffuri Expected behavior is quite specific unfortunately, and some users rely on strict interpretation and do not want coercions. This is why there are separate "getValueAsXxx()" methods. On the other hand, adding those adds to implementation complexity (for all supported formats).
However, adding something like 'getValueAsDecimal()' might be feasible.

Original intention was for streaming parsers to remain simple, and handle necessary conversions/coercions on data-binding level. And in this case this would work if you were not writing custom deserializer.

Actually one thing that could simplify your work would be to use a `Converter`, to request data-binder to bind data into `BigDecimal` (which it knows how to do), and your converter would just convert from that to `Timestamp`. Just a possible improvement; I realize that you can make this work with full deserializer as well.
