### ISSUE TITLE
xml serialization to Mapper skipped nodes

### ISSUE THREAD

**Issue by damianszczepanik** [FasterXML/jackson-dataformat-xml#161]
I'm uisng JSON converstion and now to pass XML I've changed mapper to `XmlMapper`. but when passing 

```
<?xml version="1.0" encoding="UTF-8"?>
<root>
   <accessories>
      <element>sunroof</element>
      <element>radio</element>
   </accessories>
</root>
```

I get

```
<LinkedHashMap xmlns="">
    <accessories>
        <element>
           <value>radio</value>
        </element>
    </accessories>
</LinkedHashMap>
```

so sunroof is missed. What's wrong with my code? I couldn't find good example on Wiki.

**Comment by cowtowncoder** [comment]
Can you show what you are actually doing in code? XML content alone does not tell much about processing.

**Comment by damianszczepanik** [comment]
Take a look at this PR https://github.com/damianszczepanik/silencio/pull/43

First I've tried to implement one solution found 
https://github.com/damianszczepanik/silencio/commit/3ca9cbc2ad6ec5ad37d6b7afa2dd701c677d5db0#diff-9aa71fe8aff75ff37d5a816d068b5269

then I've tried to use the same input file https://github.com/damianszczepanik/silencio/commit/3ca9cbc2ad6ec5ad37d6b7afa2dd701c677d5db0#diff-efdaec148247975bbc8bc85913ca8bd2

for another conception https://github.com/damianszczepanik/silencio/commit/3ca9cbc2ad6ec5ad37d6b7afa2dd701c677d5db0#diff-edc4af6be9a1a097442d376156b3cf1c

So I believe the way I create and init XmlMapper is not correct or there is some limitation

**Comment by cowtowncoder** [comment]
I'm sorry but while I can guess on pieces that go wrong , example is still too big for a unit test.

But fundamentally I think that your attempt to convert between JSON and XML via non-POJO class is not going to work too well, because Jackson XML module is really designed to support reading and writing POJOs. Non-typed approaches via `Map`s, `List`s and arrays, or `JsonNode`, may or may not work; they are not officially supported. Since "any-setter" and "any-getter" are effectively dealing with untyped Maps, they may or may not work as well.

If you do want to do such automated conversions, you may be better off actually using direct XML access via Stax API (`XMLStreamReader`, `XMLStreamWriter`); and Jackson only for JSON read/write of untyped content; either via streaming API or databind.
Writing a simple stream reader and writer using Stax API is straight-forward, and could work well with Jackson `JsonParser` and `JsonGenerator`. This would also not require keeping the whole input (or output) in memory.

**Comment by damianszczepanik** [comment]
Can you share some example how to load xml into the Map? I could do this smoothly with json but using the same way for xml does not work

**Comment by cowtowncoder** [comment]
As I said, Jackson XML module is designed to work with POJOs, not Maps (which are not POJOs).
Expectation is that there is enough type and property name information to handle impedance problems (XML has, for example, no distinction between "arrays" and "objects", without additional metadata).
Even JAXB requires additional converters/handlers to deal with Maps.

**Comment by cowtowncoder** [comment]
I know there are issues wrt handling of `Map` type, but need separate issue for concrete plans (possibly allow changing of structure used in XML f.ex), so closing this particular issue.
