### ISSUE TITLE
Failure to deserialize double values as doubles

### ISSUE THREAD

**Issue by richmidwinter** [FasterXML/jackson-dataformat-xml#175]
If I have a junit test that looks like:

```
	@Test
	public void testDoubleSerialisation() throws Exception {
		ObjectMapper mapper = new XmlMapper();
		Map<String, Object> record = new HashMap<>();
		double dbl = 20.0;
		record.put("key", dbl);
		
		String json = mapper.writeValueAsString(record);
		
		JsonNode newRecord = mapper.readTree(json);
		assertEquals(DoubleNode.class, newRecord.get("key").getClass());
	}
```

Then it fails - the record is deserialized as a TextNode, not a DoubleNode. Change XmlMapper to ObjectMapper and it the test passes (but I have to serialize to XML so using JSON doesn't actually help me).

**Comment by cowtowncoder** [comment]
Thank you for reporting this.

I'll have a look, but one thing to keep in mind is that XML module does not fully support tree model (`JsonNode`), since XML infoset does not really match well with JSON-based model.
Second, `Map`s do not work very well either, especially as root values (main value being read or written).

So the usage is not strictly speaking supported or guaranteed to work.
If I can improve handling easily I will do that.

**Comment by cowtowncoder** [comment]
Actually looking at the test itself, this will not work (and can not be made to work), since XML has no way to indicate that a cdata value is of specific type; and no type is implied with tree conversion. Jackson will not try to infer type from textual representation since that leads to other kinds of problems (unintended conversion to int/boolean from various textual values).
