### ISSUE TITLE
localName = "" is not honored in @JacksonXmlElementWrapper

### ISSUE THREAD

**Issue by hhimanshu** [FasterXML/jackson-dataformat-xml#181]
I have a class that looks like

``` java
public class UserActivityList {

  @JacksonXmlProperty(localName = "username")
  private String userName;

  @JacksonXmlElementWrapper(useWrapping=false, localName = "user_activity")
  private List<UserActivity> userActivity;

  public void setUserActivity(List<UserActivity> userActivity) {
    this.userActivity = userActivity;
  }

  @Override
  public String toString() {
    return "UserActivityList{" +
        "userName='" + userName + '\'' +
        ", userActivity=" + userActivity +
        '}';
  }
}
```

When I run this code, I get the following error

```
[main] ERROR c.e.tenant.internal.StealthWatch - Error in parsing response from Stealthwatch: {}
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "user_activity" (class com.project.tenant.internal.response.UserActivityList), not marked as ignorable (2 known properties: "userActivity", "username"])
 at [Source: java.io.StringReader@3059cbc; line: 10, column: 33] (through reference chain: com.project.tenant.internal.response.StealthWatchResponse["service"]->com.project.tenant.internal.response.Service["action"]->com.project.tenant.internal.response.Action["user_activity_list"]->com.project.tenant.internal.response.UserActivityList["user_activity"])
```

The way I currently solve it is  

``` java
 @JacksonXmlElementWrapper(useWrapping = false)
  private List<UserActivity> user_activity;

  public void setUser_activity(final List<UserActivity> user_activity) {
    this.user_activity = user_activity;
  }
```

The detail question is [here](http://stackoverflow.com/questions/34688410/com-fasterxml-jackson-databind-exc-unrecognizedpropertyexception-unrecognized-f)
Is it a bug or I missed something?

**Comment by cowtowncoder** [comment]
@hhimanshu The problem here is that the `localName` here would be that for the wrapper element -- but you are disabling use of wrapper element, so it is indeed just ignored.

Instead, you need to use either `@JsonProperty` (Jackson annotation) or `@XmlElement` (JAXB) to specify property name; this is the name used for the element.

Now: I am not sure what JAXB interpretation of this situation would be; if the annotation usage you show would work correctly with JAXB, I am willing to see if XML module could be changed to consider this special case; it seems reasonable enough to me. That is, if there is no explicit property name specified, `useWrapping` is set to false, `localName` is not empty, consider wrapper name to override property name.
If so, let's leave this issue open. Fix would probably have to go in 2.8, however, since this change could theoretically break handling in existing code.

**Comment by hhimanshu** [comment]
@cowtowncoder, I am not sure what you are recommending, Did you mean using

```java
 @JacksonXmlElementWrapper(useWrapping = false)
  @XmlElement(name = "user_activity")
  private List<UserActivity> userActivities;
```
?
If yes, this does not work either

**Comment by cowtowncoder** [comment]
@hhimanshu  Yes, that should work, and as far as I have tested, does work. If not, I would apprecate a unit test to reproduce this; either against 2.6(.4) or 2.7.0.

**Comment by hhimanshu** [comment]
I would try to give you that

**Comment by gullerya** [comment]
For anyone that comes here for the solution (like me):
`@XmlElement(name = 'something')` is NOT working
`@JsonProperty('something')` works OKAY

**Comment by schulz-m** [comment]
Actually, for me the solution was simply to revert the order of the XmlProperty and XmlElementWrapper - then everything seems to work as expected! For example:
```java
@JacksonXmlProperty(localName = "Command")
@JacksonXmlElementWrapper(useWrapping = false)
public List<Command> lala;
```

**Comment by cowtowncoder** [comment]
@schulz-m That is... interesting. Ordering should not make any difference since it is not something code can observe, nor take into account.

**Comment by schulz-m** [comment]
@cowtowncoder After your comment I tried it out again and it seems that some other change made it work for me, so please ignore my comment - excuse the confusion :-)
