### ISSUE TITLE
XML serialization with mixin, trying to customize collection name using @JacksonXmlElementWrapper

### ISSUE THREAD

**Issue by ramukima** [FasterXML/jackson-dataformat-xml#185]
I have the following code -
1. Class Foo is generated using a schema and I can not modify it.

```
public class Foo {
    @JsonProperty("name")
    private String name;
    public Foo(String name) {
        this.name = name;
    }
}
```
1. Class Bar is generated using a schema and I can not modify it.

```
public class Bar {
    @JsonProperty("foos")
    private List<Foo> foos = new ArrayList<Foo>();

    @JsonIgnore
    public void setFoos(List<Foo> foos) { this.foos = foos; }
    public List<Foo> getFoos() { return this.foos; }
}
```
1. A Test class to serialize Bar to XML -

```
class Test {
    public static void main(String[] args) throws Exception {
        ObjectMapper mapper = new XmlMapper();

               JacksonXmlModule jmodule = new JacksonXmlModule();
        jmodule.setDefaultUseWrapper(true);     
        mapper.registerModule(jmodule);

        Foo f1 = new Foo("foo-1");
        Foo f2 = new Foo("foo-2");
        List<Foo> foos = new ArrayList<Foo>();
        foos.add(f1);
        foos.add(f2);

        Bar b = new Bar();
        b.setFoos(foos);
        System.out.println("XML:" + mapper.writeValueAsString(b));
    }
}
```
1. The XML produced is -

```
<Bar xmlns=""><foos><foos><name>foo-1</name></foos><foos><name>foo-2</name></foos></foos></Bar>
```
1. I want to change the default wrapper name to 'foos' and element name to 'foo', so I create a mixin as below -

```
public interface BarMixin {
    @JacksonXmlProperty(localName = "foo")
    @JacksonXmlElementWrapper(localName = "foos")
    public List<Foo> getFoos();
}
```
1. Added the following to the mapper in my Test class -

```
mapper.addMixIn(Bar.class, BarMixin.class);
```
1. Running the Test class after this, the XML generated looks like -

```
<Bar xmlns=""><foos><foo><name>foo-1</name></foo><foo><name>foo2</name></foo></foos><foos><foos><name>foo-1</name></foos><foos><name>foo-2</name></foos></foos></Bar>
```

Expected Outcome: 

```
<Bar xmlns=""><foos><foo><name>foo-1</name></foo><foo><name>foo-2</name></foo></foos></Bar>
```

Not sure if this is a bug. Am I expecting a wrong output with this code ? If so, I am not sure how can I achieve this using MixIn. I understand I can write custom serializer to arrive to the expected XML. However, I am trying to see if it is possible using a MixIn.

**Comment by ramukima** [comment]
A JsonIgnoreProperty on the BarMixin like below produces the expected outcome:

```
@JsonIgnoreProperties({ "foos" })
```

**Comment by cowtowncoder** [comment]
The problem is that use of `@JsonProperty` AND `@JsonIgnore` is legal -- in this case, it is considered a "split" use case. It is possible to override either one via mix-in; for example, with `@JsonIgnore(false)` (which means "ignore this JsonIgnore"; used to mask annotation from base class).

One thing to try, first, is that if you are using an older version, try Jackson 2.7.0. There are some fixes to List handling.

**Comment by cowtowncoder** [comment]
@ramukima Ok this is interesting case. The problem comes from combination of annotation in the field `foos`, and then mixin for getter method -- this resulted in property "splitting", probably because of unnecessary `@JsonIgnore` on setter method.

What is needed to fix this, to reconcile things is to for example add mix-in on field, not getter. Something like:

```java
    public abstract class BarMixin {
        @JacksonXmlProperty(localName = "foo")
        @JacksonXmlElementWrapper(localName = "foos")
        List<Foo> foos;    
    }
```

where access for `foos` does not matter: only name and type need to match.

Doing this will produce expected output.
