### ISSUE TITLE
scala+xml modules deserialize Option[String] into Option[Int]

### ISSUE THREAD

**Issue by jendap** [FasterXML/jackson-dataformat-xml#195]
Using latest jackson scala and xml modules (with woodstox) has deserialize Option[String] into Option[Int].

``` scala
case class Foo(maybeInt: Option[Int])

val xmlMapper = new com.fasterxml.jackson.dataformat.xml.XmlMapper()
xmlMapper.registerModule(com.fasterxml.jackson.module.scala.DefaultScalaModule)
val foo = xmlMapper.readValue("<foo><maybeInt>42</maybeInt></foo>", classOf[Foo])
foo.maybeInt.get shouldBe 42 // FAIL: "42" was not equal to 42
foo.maybeInt.map(identity) shouldBe Some(42) // FAIL: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
```

Using just Int works fine (or java.lang.Integer for nullable fields) but the scala option type gets inferred wrong.

Note: Json module (with the same jackson version - 2.7.3) works jut fine...

``` scala
val objectMapper = new com.fasterxml.jackson.databind.ObjectMapper()
objectMapper.registerModule(com.fasterxml.jackson.module.scala.DefaultScalaModule)
val jsonFoo = objectMapper.readValue("""{"maybeInt": 42}""", classOf[Foo])
 jsonFoo.maybeInt.get shouldBe 42 // WORKS
jsonFoo.maybeInt.map(identity) shouldBe Some(42) // WORKS
```

**Comment by cowtowncoder** [comment]
It would be great if this could be reduced with just XML and standard databind. `AtomicReference` is handled similar to `Option`, as far as type handling goes. The problem with Scala reproduction is that I don't do Scala, and conversely Scala module maintainers do not know well workings of xml module (plus Scala module itself is bit under-maintained). So basically if scala part could be skipped (since I assume it may work correctly given that json handling works), solving the underlying problem (which in all likelihood is in xml handling, or its interaction with `jackson-databind`) it would be more likely this problem gets fixed.

**Comment by cowtowncoder** [comment]
Can not reproduce without plain-Java reproduction; may be reopened with test case.
