### ISSUE TITLE
Is it possible to generate XSD from list of POJOs?

### ISSUE THREAD

**Issue by ilgrosso** [FasterXML/jackson-dataformat-xml#202]
How much difficult would be to generate an XSD file out of a collection of possibly Jackson-annotated POJOs?

Thanks!

**Comment by cowtowncoder** [comment]
@ilgrosso I haven't tried to do that, but since we already generate other types of schemas (JSON Schema, Avro Schema, protoc), I would building something would be doable.

In future, please use `jackson-dev` list for discussion related to development (or, `jackson-user` for usage). List members might be aware of components outside of Jackson that perhaps already exist.

If the question is about whether `jackson-dataformat-xml` does this, answer is no. There are also no plans to add such support in this component; intent is to stay out of Schema and validation work.
But similar to JSON Schema, implementing a separate lib/module (`jackson-module-jsonSchema`) is possible as a sort of add-on.

**Comment by ilgrosso** [comment]
Subscribed `jackson-user` and posted the question above there, it seems my message needs to go through moderation...
