### ISSUE TITLE
Can't deserialise an empty tag into an instance with no fields

### ISSUE THREAD

**Issue by jlous** [FasterXML/jackson-dataformat-xml#209]
As noted in #89:
- jackson deserializes `<x></x>` and `<x/>` for leaf-nodes as NULL.. 
- JAXB deserializes `<x></x>` or `<x/>` for leaf-nodes not as NULL-values but provides default-values (an integer will be 0 by default).

This is a big problem for me. I need to deserialize a third-party schema which represents some state using the _presence_ of a tag, in some cases with no children or attributes

```
   <myObject>
       <someStructuredData>...</someStructuredData>
       <flag1/>    
       <flag3/>
   </myObject>
```

This maps naturally to fields that can be null or populated with objects that are dumb, but typed:

```
   class myObject{
       SomeStructuredData someStructuredData;
       Flag1 flag1;
       Flag2 flag2;
       Flag3 flag3;
   }
```

After deserializing the example above I want flags 1 and 3 to be populated, and flag 2 to be null.

But I can find no way to get Jackson-xml to deserialise empty tags to anything but null.
Is it truly not supported, or am I just missing something? Discerning meaningfully between missing and empty tags is a perfectly valid use of xml, and should be supported in some way or other.

**Comment by cowtowncoder** [comment]
Note that explicit `null` is indeed different from no value at all, so Jackson does distinguish this.
So one thing that might work is to have setter methods that translate `null`s to some other state change; setter is not called if element is not encountered.

I agree in that handling of empty values is not optimal, but haven't figured a good way to handle it better.

**Comment by markaren** [comment]
Just encountered this issue my self. The XML I'm parsing uses a child tag to define the type of the object. 
Example:

```xml
<ModelVariables>
  <ScalarVariable name="h" valueReference="0" description="height, used as state"
                  causality="local" variability="continuous" initial="exact">
    <Real start="1"/>
  </ScalarVariable>
  <ScalarVariable name="der(h)" valueReference="1" description="velocity of ball"
                  causality="local" variability="continuous" initial="calculated">
    <Real />
</ModelVariables>
```
From the above XML, the first list element gets serialized to a RealVariable because it contains the (non-empty) Real tag. The second case breaks the application because the tag is empty -> the field that decides the object type is set to null!

**Comment by cowtowncoder** [comment]
Jackson 2.9 added one new feature for `@JsonSetter`, for null handling:

https://medium.com/@cowtowncoder/jackson-2-9-features-b2a19029e9ff

(see "Null replacement/error/skipping (on deserialization)")

wherein annotating property as:

    @JsonSetter(nulls=Nulls.AS_EMPTY)

should result in `null` being coerced into "empty" value of the type.
For POJOs this should be newly constructed instance (and if so, requires no-arg constructor, NOT any other kind of creator).

Problem otherwise is that due to separate of streaming parser, databinding, lower level must decide in how to expose value, and as things are there is not enough information to be able to expose it either as `null` OR as `START_OBJECT`/`END_OBJECT` pair (since parser has no knowledge of what expected target at high level might be).

I will add tests in XML module to ensure that this approach works (or, if not, that it needs to be fixed).

**Comment by cowtowncoder** [comment]
One other thing: it is also possible to configure null-handling for type via `mapper.configOverrides(type).setSetterInfo(MyClass.class)`, or even as global default:

    mapper.setDefaultSetterInfo(...)

(examples can be found from test cases under `src/test/java/com/fasterxml/jackson/databind/deser/filter/NullConversionsGenericTest.java`

I hope this helps.

**Comment by markaren** [comment]
```java
@JsonSetter(nulls=Nulls.AS_EMPTY)
```
did the trick for me. Now I can replace JAXB with Jackson :)

**Comment by cowtowncoder** [comment]
@markaren yay!
