### ISSUE TITLE
Cannot write XML via JsonGenerator/ToXmlGenerator anymore

### ISSUE THREAD

**Issue by Corni** [FasterXML/jackson-dataformat-xml#216]
Hi,

we use Jackson (version 2.6.7) to output large volumes of data as either XML or JSON.
Recently, we tried upgrading to 2.8.5, but got stuck with the following bug.

Our code looks (reduced) like this:
```java
		XmlFactory xmlFactory = new XmlFactory();
		xmlFactory.configure(ToXmlGenerator.Feature.WRITE_XML_DECLARATION, true);
		try {
			JsonGenerator generator = xmlFactory.createGenerator(new OutputStream() {
				@Override
				public void write(int b) throws IOException {
					System.out.write(b);
				}
			}, JsonEncoding.UTF8);

			((ToXmlGenerator) generator).initGenerator();
			generator.writeFieldName("blabla");
			generator.writeStartObject();

		} catch (IOException e) {
			e.printStackTrace();
		}
```

Since the fix for 282 (jackson-core), writeFieldName doesn't work in a non-object context, throwing 
"com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value".
But (at least for XML)ToXmlGeneator::writeStartObject() calls _handleStartObject(), which then checks for nextName == null - which is the case, because you can't use writeFieldName anymore to set _nextName.
Thus, if you comment out the writeFieldName, you get
"java.lang.IllegalStateException: No element/attribute name specified when trying to output element".

Is our code wrong? Was this never intended to be working?
Do we need to use ((ToXmlGenerator) generator).setNextName();?

**Comment by cowtowncoder** [comment]
As a general thing, users are encouraged to avoid using streaming API with XML. There are quite a few edges that databinding tries to smooth out. But since this is sometimes unavoidable (with custom (de)serializers) ideally things would work.

But in the code above what you are missing is the initial `writeStartObject()`. Earlier versions did indeed miss checks for state in some places, but it is surprising that code worked.
I think you do indeed need to call `setNextName()`: code in `XmlSerializerProvider` handles initialization for data-binding, if you want to see an example.

**Comment by Corni** [comment]
Well,

```java
		XmlFactory xmlFactory = new XmlFactory();
		xmlFactory.configure(ToXmlGenerator.Feature.WRITE_XML_DECLARATION, true);
		try {
			JsonGenerator generator = xmlFactory.createGenerator(new OutputStream() {
				@Override
				public void write(int b) throws IOException {
					System.out.write(b);
				}
			}, JsonEncoding.UTF8);

			((ToXmlGenerator) generator).initGenerator();
			generator.writeStartObject();
			generator.writeFieldName("blabla");

		} catch (IOException e) {
			e.printStackTrace();
		}
```
doesn't work either and throws a "IllegalStateException: No element/attribute name specified when trying to output element"

Anyways, using
```java
		XmlFactory xmlFactory = new XmlFactory();
		xmlFactory.configure(ToXmlGenerator.Feature.WRITE_XML_DECLARATION, true);
		try {
			JsonGenerator generator = xmlFactory.createGenerator(new OutputStream() {
				@Override
				public void write(int b) throws IOException {
					System.out.write(b);
				}
			}, JsonEncoding.UTF8);

			((ToXmlGenerator) generator).setNextName(new QName(null, "blablabla"));
			((ToXmlGenerator) generator).initGenerator();
			generator.writeStartObject();
		} catch (IOException e) {
			e.printStackTrace();
		}
```
does work for us, so if you don't see a bug here, you can close the issue.
Thanks!

**Comment by cowtowncoder** [comment]
@Corni I specifically said:

"I think you do indeed need to call setNextName(): code in XmlSerializerProvider handles initialization for data-binding, if you want to see an example."

so it's not that odd that code that does not do fails. I specifically pointed to `XmlSerializerProvider` which has (minus comments):

```java
    protected void _initWithRootName(ToXmlGenerator xgen, QName rootName) throws IOException
    {
        if (!xgen.setNextNameIfMissing(rootName)) {
            // however, if we are root, we... insist
            if (xgen.inRoot()) {
                xgen.setNextName(rootName);
            }
        }
        xgen.initGenerator();
        String ns = rootName.getNamespaceURI();
        if (ns != null && ns.length() > 0) {
            try {
                xgen.getStaxWriter().setDefaultNamespace(ns);
            } catch (XMLStreamException e) {
                StaxUtil.throwXmlAsIOException(e);
            }
        }
    }
```

which does the trick; first, set name of next element (because whereas in JSON Object start marker has no name (it's `{`), in XML element start marker contains name. Since serializers only provide name for properties, there is this off-by-one problem which is solved requiring this cumbersome call.
