### ISSUE TITLE
jackson supporting package level annotation of @XmlJavaTypeAdapter

### ISSUE THREAD

**Issue by vasilhsfoto** [FasterXML/jackson-dataformat-xml#221]

**Comment by vasilhsfoto** [comment]
Using Jersey 2.22.1 registering JacksonSerializer version of Jackson used is 2.7.2

I would like to use the annotation @XmlJavaTypeAdapter at package level so that my adapter to be applied to all the types referenced under this package.

Is that supported by Jackson ? I saw somewhere that package level annotations may or may not be supported 

However, I don't see issues when I apply the annotation on field or method (i.e get) level

**Comment by cowtowncoder** [comment]
Package annotations are fundamentally incompatible with the way Jackson uses annotations, so they are not supported. Problem is that it would not be clear what the precedence of package annotations would be, relative to annotations in inheritance hierarchy.

In theory it could be possible to support some subset of package annotations, those that would register handlers (instead of applying to specific type).
But there are no current plans to add such support.

**Comment by cowtowncoder** [comment]
As per earlier comment, no plans to add support for package-level annotations (if those were wanted, this would belong to `jackson-databind`, however, so may re-file there)
