### ISSUE TITLE
uninstantiated char cannot be serialized to XML String using writeValueAsString

### ISSUE THREAD

**Issue by Daimanta** [FasterXML/jackson-dataformat-xml#265]
Using jackson-dataformat-xml version 2.8.10, I ran some tests to see how the functionality of the XML writer worked and I ran upon a bug when trying to serialize an uninstantiated 'char'. Trying to do this results in an IOException with the message 

"Unexpected IOException (of type java.io.IOException): java.io.IOException: Invalid null character in text to output" at the following points:
 at com.fasterxml.jackson.databind.JsonMappingException.fromUnexpectedIOE(JsonMappingException.java:333)
at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3077)

I quickly deduced that instantiating the 'char' in my POJO solved the issue. The Jackson JSON serializer works as intended (rendering "\u0000") as the field value.

How to reproduce the error:

1. Create POJO with char field
2. Do not instantiate the char field
3. Call mapper.writeValueAsString(POJO) on the POJO with the XML mapper
4. Get IOException as expected
5. (Try again with instantiated char to solve the issue)

Desired result: the 'char' is serialized in a similar manner to the POJO serializer (like the NUL character).

**Comment by cowtowncoder** [comment]
That's right: XML specification forbids inclusion of null character (Unicode value of 0), not even if escaped, so this seems like proper behavior here?

**Comment by Daimanta** [comment]
The failure of the system may be correct, however the codebase also states:

"} catch (IOException e) { // shouldn't really happen, but is declared as possibility so:
            throw JsonMappingException.fromUnexpectedIOE(e);
        }"

The error that returns from the system is very non-descriptive. Sure, there was a NUL byte and this is not allowed, but where did it occur? Since the XML writer is aware of the context, a better location could be found for the error, that is the Mapper should indicate the location where it went wrong. When relying on external data, going on a wild goose chase for the magic NUL byte is a hassle so a better error is surely welcome.

**Comment by cowtowncoder** [comment]
Always good idea to improve error messages, so I'll consider this as such an idea.

Maing challenge is that Jackson is using a Stax parser/generator, it does not actually have knowledge of what is happening aside from exception, and trying to pre-validate content seems problematic (since that'd mean Jackson side would have to implement same XML validation; that also adds significant overhead).

So it may be that all that can be done is to see that exception wrapping works as expected.
Stax API only exposes a single exception if I remember correctly (`XMLStreamException`), and although implementation may have sub-classes (Woodstox does at least) relying on impl-dependant types would prevent using other Stax implementations.

**Comment by Daimanta** [comment]
Ok, I understand the difficulties that arise from exceptions thrown by external libraries but any information on the source of the error would naturally be welcome :)

**Comment by cowtowncoder** [comment]
Not sure how I could proceed: may be reopened with more specific example (reproduction with one of recommended XML parsers).
