### ISSUE TITLE
Deserialize Collection of tags not on place

### ISSUE THREAD

**Issue by Fornori** [FasterXML/jackson-dataformat-xml#279]
Hello.

When i try to parse this xml:
```
<gen:link xlink:type="extended" xlink:role="http://www.cbr.ru/xbrl/nso/ins/rep/2017-12-31/tab/sr_0420150">
        <va:valueAssertion xlink:type="resource" xlink:label="valueAssertion" xlink:title="valueAssertion"
                           id="valueAssertion_sr_0420150_01" test=" $OkopfEnumerator" aspectModel="dimensional"
                           implicitFiltering="true"/>
        <variable:factVariable xlink:type="resource" xlink:label="factVariable" xlink:title="factVariable"
                               id="factVariable" bindAsSequence="false"/>
        <va:valueAssertion xlink:type="resource" xlink:label="valueAssertion_2" xlink:title="valueAssertion_2"
                           id="valueAssertion_sr_0420150_02" test=" $OkfsEnumerator" aspectModel="dimensional"
                           implicitFiltering="true"/>
</gen:link>
```

With this code:

```
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class Section {

    @JacksonXmlProperty(namespace = "xlink", localName = "role", isAttribute = true)
    private String role;

    @XmlElement(namespace = "va", name = "valueAssertion")
    private List<ValueAssertion> valueAssertion;
}
```

The variable valueAssertion only contains 1 element, but I expect = two. But if I remove variable:factVariable all is good. So is any hack to Jackson start parse in right way this file?

**Comment by nogoodbay** [comment]
I have the same problem.
I found that it only treat sequential tag to array.
So, if i have such xml fragment:
<root />
 <a />
 <a />
 <b />
 <b />
 <b />
 <a />
</root>

I expect i could get a  List<a> and List<b> which size is 3. but List<a> size is 1, List<b> size is 3.

**Comment by cowtowncoder** [comment]
Hmmh. Test case is broken in multiple ways (missing `ValueAssertion` definition; broken XML that is missing namespace declarations), making this difficult to reproduce.

However: the problem is that XML does not have `<valueAssertion>` elements as a sequence, as there is intervening `<factVariable>`, so this will be dealt as if there were 2 lists, latter replacing former.
If elements can not be made to be in sequence, a work-around is needed in which there is setter method like

```java
public void setValueAssertion(List<ValueAssertion> assertions) {
   valueAssertion.addAll(assertions);
}
```

and make sure to either check for `null`, or initialize `assertions` to empty list.
