### ISSUE TITLE
Jackson 2.10.x fails to deserialize xsi:nil with multiple child elements

### ISSUE THREAD

**Issue by henrik242** [FasterXML/jackson-dataformat-xml#378]
This XML:
```
<Silly xmlns:a="http://www.w3.org/2001/XMLSchema-instance" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <a:Hey i:nil="true"/>
  <a:Ho>to</a:Ho>
</Silly>
```
 .. fails to properly deserialize in Jackson 2.10.x.  Both `Hey` and `Ho` are null, while in 2.9.9 they were `""` and `"to"`.

See test project at https://github.com/henrik242/jackson-xml-nil-problem

First reported in https://github.com/FasterXML/jackson-dataformat-xml/issues/354#issuecomment-566041199 and https://github.com/FasterXML/jackson-dataformat-xml/issues/358#issuecomment-566048921

**Comment by henrik242** [comment]
Happy new year! Any ideas to a workaround or fix for this, @cowtowncoder ?

**Comment by cowtowncoder** [comment]
Happy new year!

No, unfortunately I have not had time to work on xml module. But I think I can probably add a failing test for this soon at least.

**Comment by cowtowncoder** [comment]
Hmmh. Ok, from some digging it looks like second element gets skipped for some reason.

**Comment by henrik242** [comment]
Weird. It's got something to do with using the `http://www.w3.org/2001/XMLSchema-instance` schema, at least.

**Comment by cowtowncoder** [comment]
Sort of; I think it is really "transformation" of element into `null`, skipping until end, and not properly synchronizing. I really should rewrite the backend, one of these days, but for that to happen would probably need one of 2 things to happen -- either finding XML to be higher priority than other formats (aside from json), or, find a way to maintain Jackson for living and not just as a hobby.
But I digress. :)

I think I can figure out a fix/work-around for this particular problem. It's just more difficult than it should be, because of complexity of backend implementation which at this point is patch-over-patch, transforming one stream of events into another with sort of minimal state keeping.

**Comment by henrik242** [comment]
Thanks!

**Comment by cowtowncoder** [comment]
2.10.2 now released, I hope things work as expected. Also, reports for other edge cases (if any) would be welcome.

**Comment by henrik242** [comment]
Issue #427 might be related to this
