### ISSUE TITLE
The actual item type is not serialized when working with generics

### ISSUE THREAD

**Issue by texhnolyzze** [FasterXML/jackson-dataformat-xml#382]
Hello.
We use Jackson (2.97) in our services when serializing and deserializing data. Previously, we used only the support of Json. However, recently we decided to add also support of XML.
We ran into limitations that you cannot transparently serialize/deserialize primitives (and wrappers over them). We can live with it. However, another problem emerged.
The code will explain better.

We have an abstract model:
```java
public abstract class AbstractModel<T> {

	private T value;
	
	public AbstractModel() {
	}
	
	public AbstractModel(T value) {
		this.value = value;
	}
	
	public T getValue() {
		return value;
	}
	
	public void setValue(T value) {
		this.value = value;
	}

}
```
And we have a concrete model:
```java
public class ConcreteModel extends AbstractModel<String> {
	
    public ConcreteModel() {
    }

    public ConcreteModel(String s) {
        super(s);
    }
	
}
```
We also have such **mixin**:
```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
@JsonSubTypes({
    @JsonSubTypes.Type(value = ConcreteModel.class, name = "ConcreteModel")
})
public interface AbstractModelMixin {
	
}
```
Now we want to return from our service a list of abstract models:
```java
@GET
@Path("/abstractModelsList")
@Produces(MediaType.APPLICATION_XML)
public List<AbstractModel<?>> listOfAbstractModels() {
    return List.of(new ConcreteModel("1"), new ConcreteModel("2"), new ConcreteModel("3"));
}
```
And after serialization we get such XMl:
```xml
<ListN>
	<item>
		<value>1</value>
	</item>
	<item>
		<value>2</value>
	</item>
	<item>
		<value>3</value>
	</item>
</ListN>
```
As you can see, no information about actual types of elements is included.
However, if we return `AbstractModel[]` from out service, we get proper answer:
```xml
<AbstractModels>
	<item _type="ConcreteModel">
		<value>1</value>
	</item>
	<item _type="ConcreteModel">
		<value>2</value>
	</item>
	<item _type="ConcreteModel">
		<value>3</value>
	</item>
</AbstractModels>
```
Please tell me, is this a limitation? Because we don't have such problem with JSON.

**Comment by cowtowncoder** [comment]
I think the problem is not so much polymorphic part (although combination of generics and polymorphic types can, in some cases, be problematic -- but not here as per JSON working), but that in XML support for root value is mostly for POJOs and use of root-level `Collection` or `Map` is unlike to work well.
Use of generic root values is not really recommended even in JSON (since type erasure often causes problems wrt type id not getting written on serialization, but expected on deserialization), but with XML there are additional challenges in supporting `Collection` types: basically, handling of additional element wrappers does not work for root values. This is due to implementation detail (property value handling is easier to customize), and not due to fundamental limitation.

So: if at all possible, I would recommend designing APIs to always have root-level value a POJO, not "raw" `List` or `Map`. It might be worth checking if this would work around the problem with XML (regardless of whether if change to API would be feasible or not).

Second: it would be good to isolate a test case that only uses Jackson, and not framework (Spring?) around it -- in this case, it is possible that framework is not passing necessary full type (`JavaType` or `TypeReference`) on serialization. This is something that should be problematic with JSON too though, so I am not sure if this would be it.

If reproduction is possible, maybe I could have a look to see whether I can explain specific problem out of likely candidates I have mentioned above.

**Comment by texhnolyzze** [comment]
Thanks for the answer!
I ended up solving my problem with your hint about `JavaType`. You're right, I was not passing necessary full type on serialization. Previously, I serialized an object this way:
```java
public void writeTo(Object o, Class<?> type, Type genericType, Annotation[] annotations, MediaType mediaType, MultivaluedMap<String, Object> httpHeaders, OutputStream entityStream) throws IOException {
        xmlMapper.writeValue(outputStream, object);
    }

```
But doing so:
```java
public void writeTo(Object o, Class<?> type, Type genericType, Annotation[] annotations, MediaType mediaType, MultivaluedMap<String, Object> httpHeaders, OutputStream entityStream) throws IOException {
        xmlMapper.writerFor(xmlMapper.getTypeFactory().constructType(genericType)).writeValue(entityStream, o);
    }
```
solved my problem and now all tests are passing. Thanks!

**Comment by cowtowncoder** [comment]
@texhnolyzze Ah. Excellent! I am glad it worked out that way -- this is one of problem areas, due to JDK's limited support for specifying generic types. Frameworks struggle with it; Jackson JAX-RS provider has a few work-arounds here and so on.
