### ISSUE TITLE
Fields of same name conflicting even with one being an attribute and the other a child

### ISSUE THREAD

**Issue by Bokoblin** [FasterXML/jackson-dataformat-xml#383]
Hello,

I'm currently developing a library to enable conversion between MSML with custom elements and Java's POJOs. I have encountered several issues related to jackson (de)serialization in the last few weeks needing workarounds that I would prefer to avoid.
I have already dug over issues there and tentative solutions before posting here.

This issue report concerns the impossibility to define multiple fields with the same name, though one is an attribute and the other a child.
Ideally, jackson should be able to identify that they are not in conflict because of this distinction.

This issue occurs to me on the element **Event** from [RFC 5707](https://tools.ietf.org/html/rfc5707#section-7.4) having the following MSML representation:
```
<event name="msml.conf.my_element" id="conf:example">
 <name>my_element</name>
 <value>conn:abc123</value>
</event>
```
I have implemented it as follow :
```
@JsonInclude(JsonInclude.Include.NON_NULL)
@JacksonXmlRootElement(localName = "event")
public class Event {
    @JacksonXmlProperty(localName = "name", isAttribute = true)
    private String name;

    @JacksonXmlProperty(localName = "id", isAttribute = true)
    private String id;

    @JacksonXmlProperty(localName = "name")
    private String bodyName;

    @JacksonXmlProperty(localName = "value")
    private String value;
}
```

You can see there that the field name is both present as an attribute and a child, and considering it is an RFC, changing one of the field name is not a valid solution.

Attempting a serialization with the above code results in the following exception:
``com.fasterxml.jackson.databind.JsonMappingException: Multiple fields representing property "name": Event#name vs Event#bodyName``.

I have attempted overcoming this problem using @JsonAnyGetter/Setter and a map, or by defining the second name as a pojo, to no avail.
As a temporary solution, I have used internally an alternative name **_name**, and after serializing/before deserializing I add some overhead wit ha string query replace.
However you can easily see that it is not a suitable solution and it becomes quite a problem if the string length gets bigger.

If you need more information, please tell me.

P.S. This issue look to be related to the problems encountered in issue #65, but the effects and goals seem different, and the issue is 5 years older.

System information
---
Java version : 11
Jackson version : jackson-dataformat-xml@2.10.2
Woodstox : woodstox-core@6.0.3

**Comment by cowtowncoder** [comment]
Unfortunately there is no real way to make attribute/element names to differ on deserialization side: they are considered essentially equivalent. This is mostly since such distinction does not exist in JSON (nor pretty much any other supported format aside from XML): on serialization side it can be expressed (to output one or the other), but not ion input side.

This is unlikely to change in future.

**Comment by Bokoblin** [comment]
Okay too bad, do you have another better workaround idea than the one I use to overcome this issue?

Concerning your json representation, maybe it could have been a possibility to add a prefix or suffix to elements with "attributes=true" in the internal representation and when doing the XML->JSON conversion

**Comment by cowtowncoder** [comment]
@Bokoblin on prefix: although I dislike that approach (I know that some systems use `@` for attributes) in general, I guess ability to enable prefix for XML format module is not a bad idea. I am not a big fan of it as general rule (i.e. that a tool/library would automatically do it for everything), but as a configurable naming convention of sort... maybe? It might be relatively easy for serialization side.

Then again, I am not sure it could be made to work, actually, since this would only help with mapping XML representation (so `@` would be logically added on write, removed when reading) to logical name, but not really separate internal property.
That is, real distinction would need to be on POJO side: how to keep 2 apart at that level, but mapped to same external name.

So I am not quite sure how this could be handled, although I do understand the problem itself.

**Comment by cowtowncoder** [comment]
Actually realized there is an older issue for the elem-vs-attribute problem, #65. Will close this issue in favor of that one.

**Comment by kamransaleem** [comment]
i'm stuck on this issue too, unfortunately I cannot change the source XML that i'm deserializing as it's not mine.  Any workarounds?
