### ISSUE TITLE
Error reading byte array XML with encoding WINDOWS-1252

### ISSUE THREAD

**Issue by marcieldeg** [FasterXML/jackson-dataformat-xml#428]
**Describe the bug**
Error reading byte array XML with encoding WINDOWS-1252.:
Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: N/A

**Version information**
2.11.3

**To Reproduce**
```
public class Main {
	private static final String xml = "<?xml version=\"1.0\" encoding=\"WINDOWS-1252\"?><x/>";

	public static void main(String[] args) throws Exception {
		new XmlMapper().readValue(xml.getBytes(), new TypeReference<Map<String, Object>>() {});
	}
}
```
If I change to read XML from String ou ByteArrayInputStream, it works.

**Comment by cowtowncoder** [comment]
Interesting. Thank you for reporting this, @marcieldeg. I wonder if this might be an issue with Woodstox, specific to WINDOWS-1252 encoding.

**Comment by cowtowncoder** [comment]
Interestingly enough, a work-around is to construct `ByteArrayInputStream` around `byte[]` like so:

```
        final byte[] b = xml.getBytes("UTF-8");
        try (InputStream in = new ByteArrayInputStream(b)) {
            new XmlMapper().readValue(in, Map.class);
        }

```

This obviously shouldn't be needed (I'll see how to fix this), but for now that might prove useful.

**Comment by cowtowncoder** [comment]
Yes, the problem was with Woodstox handling: oddly enough tests hadn't covered this case (helper methods construct input from `InputStream` or `Reader`, but not using underlying method for passing byte array) -- noting, however, that more common encodings (namely, "UTF-8", "US-ASCII", Latin-1) would not fail this way; only ones for which JDK decoder needed.

Woodstox 6.2.3 released with fix; will update dependency by this module for next release versions.
In the meantime can either use the work-around mentioned above, or explicitly use newer Woodstox version.
