### ISSUE TITLE
Stax2-api 3.x is not compatible after jackson-dataformat-xml 2.9

### ISSUE THREAD

**Issue by DavyKoravand** [FasterXML/jackson-dataformat-xml#444]
Hi, since 2.9 I noticed that this library has updated stax2-api to 4.x. However, this seems to make jackson incompatible with any library that uses stax2-api 3.x. Is there any way around this besides keeping jackson on version 2.8 or removing the other dependency (which isn't realistic in our case)?

**Comment by cowtowncoder** [comment]
Can you elaborate on type of incompatibility? I vaguely recall there being some issues, but I think that one thing to do is to ensure that `stax2-api` versions (and those of libraries that depend on it, mostly `Woodstox` and `Aalto`) are using latest patch version:

* For stax2-api, `4.2.1` (for 4.x) and `3.1.4` (for 3.x)
* For Woodstox and Aalto similarly latest patch of major version

**Comment by DavyKoravand** [comment]
In my case, the axis2-kernel library uses Woodstox 4.x (which still relies on stax2-api 3.x). They haven't updated in a long time which unfortunately makes newer jackson libraries incompatible with them.

**Comment by cowtowncoder** [comment]
I would suggest attempting to use 4.x stax2-api nonetheless (but specifically 4.2.1), even if having to use Woodstox 4.x.
Change by stax2-api from 3.x to 4.x did not actually change package, maven artifact or class names but was due to JDK baseline increase.

Alternatively I do not think Jackson XML module is very picky on Woodstox version itself. Since Woodstox class and package names have remained the same, too, across 4.x, 5.x and 6.x, older version may well work (minus minor bug fixes to Woodstox functionality itself).

**Comment by cowtowncoder** [comment]
At this point not clear on specific compatibility issue: would need more details to help; closing for now (may be reopened with more info -- tagging as "need test case" to indicate that)
