### ISSUE TITLE
Coercion of empty Strings defaults to CoercionAction.AsEmpty in 2.12.1

### ISSUE THREAD

**Issue by perdurabo476** [FasterXML/jackson-dataformat-xml#453]
After upgrading from Jackson 2.10.4 to 2.12.1 we experience deserialization issues for empty Tags in XML configuration files.
The problem seems to be caused by the default configuration of the new coercion feature for the XmlMapper (line 179) which is implemented as

```
        // 04-Jun-2020, tatu: Use new (2.12) "CoercionConfigs" to support coercion
        //   from empty and blank Strings to "empty" POJOs etc
        coercionConfigDefaults()
            // To allow indentation without problems, need to accept blank String as empty:
            .setAcceptBlankAsEmpty(Boolean.TRUE)
            // and then coercion from empty String to empty value, in general
            .setCoercion(CoercionInputShape.EmptyString, CoercionAction.AsEmpty)
```

In 2.10.4 deserialization of empty tags for POJOs caused a null value to be set, in 2.12.1 a new object using the default constructor is created instead.

We can easily work around this issue by adding the following explicit setting upon ObjectMapper creation:

`mapper.coercionConfigFor(LogicalType.POJO).setCoercion(CoercionInputShape.EmptyString, CoercionAction.AsNull);`

However, this obviously breaks compatibility in 2.x and may cause bigger problems for other users, so I'm wondering if the setting in XmlMapper should default to CoercionAction.AsNull to improve compatibility.

**Comment by cowtowncoder** [comment]
First things first: there is setting:

    FromXmlParser.Feature.EMPTY_ELEMENT_AS_NULL

value of which was changed for 2.12.2. This is likely the setting relevant to you. XML handling is tricky, and there's bit of overlap here.

As to change: if this was discussed during 2.12 Release Candidate phase, it could have been considered, but since 2.12.0 (and .1) have been released, I don't think this behavior should be changed at this point.
It is unfortunate that there is a compatibility concern but to me "empty POJO" (and `String`) seem like better matches to empty element than `null`: move in general is to try to make use of `xsi:nil` to indicate true nullability. But with XML this is a problem area no matter how it is handled, not having native null values (XML Schema's `xsi:nil` can work as sort of, kind of replacement but still).

**Comment by cowtowncoder** [comment]
At this point, I think we should not change the behavior. It would be good to improve documentation, add notes -- I am open to suggestions on where, and what to add. But closing this issues as "wont-fix".
