### ISSUE TITLE
Elements with the same name are treated as single string. 

### ISSUE THREAD

**Issue by jimmykane** [FasterXML/jackson-dataformat-xml#454]
Hi I am using the latest version `2.12.1`

The setup is 

```
        mapper.registerModule(KotlinModule())
        mapper.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, true)
        mapper.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_VALUES, true)
        mapper.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
        mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false) // @todo set this to true of course
 ```
        
I am parsing this xml 

```
<SelectionFields>
<Field>
	<Name>Y1</Name>
	<Types>
		<Type>TankPressure</Type>
		<Type>GasTime</Type>
		<Type>Ventilation</Type>
		<Type>Gas</Type>
		<Type>DiveTimer</Type>
		<Type>Temperature</Type>
		<Type>MaxDepth</Type>
		<Type>BatteryTime</Type>
	</Types>
</Field>
</SelectionFields>
						
```
						
The data classes for this part 

```
data class SelectionFields(
    val field: List<ViewSelectionField>
)

data class ViewSelectionField(
    val name: String,
    val types: List<ViewSelectionFieldType>
)

data class ViewSelectionFieldType(
    val type: String
)
```

But this fails with 

```
(although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('Temperature')
```

If I remove the List and treat it as an Obj it works  but I only get one value not all the rest as it should (a list)

```
data class SelectionFields(
    val field: List<ViewSelectionField>
)

data class ViewSelectionField(
    val name: String,
    val types: ViewSelectionFieldType
)

data class ViewSelectionFieldType(
    val type: String
)
```

Shouldn't this be a bug ? Or am I just not understanding something correct?

**Comment by cowtowncoder** [comment]
The first thing to check when troubleshooting XML module is to serialize content and see how it matches your expected structure. In case of array/Collection types, there is a common difference between wrapped/unwrapped values: Jackson defaults to "wrapped" and requires element for container property as well as each element. It is possible to remove the need (module README shows how).

But in addition single-argument constructors are tricky: if your value type has one String property, it can be expressed as either Object (in json), or as String, so for JSON we'd have one of:

```
{"value": "..."} 
"value"
```

and same goes for XML. SInce this is ambiguous for POJOs (and POKOs), it is necessary to annotate to know which input is expected. This is usually done using `@JsonCreator(mode = JsonCreator.Mode.PROPERTIES)` if expecting Object with one property (or `Mode.DELEGATING` for plain String serialization).

**Comment by jimmykane** [comment]
@cowtowncoder I am not sure I follow. 

See https://stackoverflow.com/questions/66331796/jacksonxml-simple-list-of-strings-serialization-and-desirilization 

this simple task looks really impossible with this lib. What am I missing?

**Comment by cowtowncoder** [comment]
If you did not understand what I said, try reading again.

**Comment by jimmykane** [comment]
Well in the end I did , as you can see from SO I solved this problem
however, I do find this mix of JSON vs XML anotation confusing and unneeded
especially to be obscure and not direct.

Thanks for the pointers
