### ISSUE TITLE
method that does not exist

### ISSUE THREAD

**Issue by wurangbo** [FasterXML/jackson-dataformat-xml#471]
When I upgrade to springboot 2.4.5, I got Error as below， BTW it work well in sprinhboot 2.3.8
An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:175)

The following method did not exist:

    com.fasterxml.jackson.dataformat.xml.XmlMapper.coercionConfigDefaults()Lcom/fasterxml/jackson/databind/cfg/MutableCoercionConfig;

The method's class, com.fasterxml.jackson.dataformat.xml.XmlMapper, is available from the following locations:

    jar:file:/C:/Users/HP/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.12.3/jackson-dataformat-xml-2.12.3.jar!/com/fasterxml/jackson/dataformat/xml/XmlMapper.class

The class hierarchy was loaded from the following locations:

    com.fasterxml.jackson.dataformat.xml.XmlMapper: file:/C:/Users/HP/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.12.3/jackson-dataformat-xml-2.12.3.jar
    com.fasterxml.jackson.databind.ObjectMapper: file:/C:/Users/HP/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.11.4/jackson-databind-2.11.4.jar
    com.fasterxml.jackson.core.ObjectCodec: file:/C:/Users/HP/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.11.4/jackson-core-2.11.4.jar
    com.fasterxml.jackson.core.TreeCodec: file:/C:/Users/HP/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.11.4/jackson-core-2.11.4.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of com.fasterxml.jackson.dataformat.xml.XmlMapper

**Comment by cowtowncoder** [comment]
If you have `jackson-dataformat-xml` version 2.12, then `jackson-databind` must be at least 2.12 as well -- it cannot be an earlier minor version: minor versions need to match (since dataformat-xml depends on databind and requires such minimum version). Similarly, `jackson-core` must be at least 2.12 as well as `jackson-databind` depends on core.

So I would make sure you have `jackson-databind` and `jackson-core` versions are 2.12.3, same as XML format module.
It is a good practice to make sure all Jackson components have the same version.
