### ISSUE TITLE
Have you eliminated the dependency on jakarta.xml.bind?

### ISSUE THREAD

**Issue by ShunichirouKamino** [FasterXML/jackson-dataformat-xml#519]
Thanks for the great framework.
I upgraded the following three from 2.12.4 to 2.13.2.

- jackson-databind
- jackson-dataformat-xml
- jackson-datatype-jsr310

Previously there was a transitional dependency on jakarta.xml.bind-api, which appears to have been lost with this update.

- 2.12.4
![image](https://user-images.githubusercontent.com/26453719/161021553-7f4557a5-8d0c-4508-bcb5-e2b1a338131d.png)

- 2.13.2
![image](https://user-images.githubusercontent.com/26453719/161021629-1a53ba40-794f-494f-972d-dc81df4dc38b.png)

Should I make my own dependencies on jakarta?
What is the reason for abolishing dependencies?

**Comment by cowtowncoder** [comment]
Yet, correct, XML module should not depend on JAXB since it does not use it.
So you do need to include it either explicitly, or have other component you depend on that depends on it.

Part of the reason for removal was to solve the tricky issue of "Jakarta vs JAXB" problem, where post-Oracle java extension packages moved to new Java packages (due to trademark issues, I think).

Originally this dependency was included for some interoperability reasons with JAXB module but it was always something I wanted not to have. Minimizing dependencies is a worthy goal in general.
It is only unfortunate that the dependency existed in the first place.

**Comment by ShunichirouKamino** [comment]
Thank you for your thoughtful response.

> Part of the reason for removal was to solve the tricky issue of "Jakarta vs JAXB" problem.

As you say, if you are not using the JAXB module in the first place, I think it is appropriate to delete it.
We will close it. Thank you very much.
