### ISSUE TITLE
Seems inconsistent in semantics when serializing  java values as Strings of xml and json

### ISSUE THREAD

**Issue by ifindya** [FasterXML/jackson-dataformat-xml#603]
Trying to serialize POJOs containing arrays or collections. 
Noticed that arrays or collections are handled correctly in XML when serializing:
```
<person>
	<id>0</id>
	<infos>
		<info>
			<name>Lisa</name>
			<sex>female</sex>
		</info>
		<info>
			<name>Jack</name>
			<sex>male</sex>
		</info>
	</infos>
</person>
```
But in JSON:
```
{
	"person": {
		"id": 0,
		"infos": [
			{
				"name": "Lisa",
				"sex": "female"
			},
			{
				"name": "Jack",
				"sex": "male"
			}
		]
	}
}
```

And not sure that we should get:

```
{

  "person": {

    "id": "0",

    "infos": {

      "info": [

        {

          "name": "Lisa",

          "sex": "female"

        },

        {

          "name": "Jack",

          "sex": "male"

        }

      ]

    }

  }

}

```

**We use Jackson Dataformat XML 2.15.2** 

codes:
```
@JacksonXmlRootElement(localName = "person")
@JsonRootName(value = "person")
public class Person {

	private int id;

	@JacksonXmlElementWrapper(localName = "infos")
	@JacksonXmlProperty(localName = "info")
	private List<Info> infos;
        
        ...
	setters and getters
        ...

	static class Info {

		public Info(String name, String sex) {
			super();
			this.name = name;
			this.sex = sex;
		}

		private String name;

		private String sex;

                 ...
		setters and getters
                 ...

	}
```

**Comment by pjfanning** [comment]
Try putting `@JsonRootName("info")` on `static class Info`. Annotations that have names starting with `JacksonXml` only affect XML (eg `@JacksonXmlProperty(localName = "info")`) and do not affect JSON.

**Comment by ifindya** [comment]
> Try putting `@JsonRootName("info")` on `static class Info`. Annotations that have names starting with `JacksonXml` only affect XML (eg `@JacksonXmlProperty(localName = "info")`) and do not affect JSON.

Adding `@JsonRootName` on `Info `like below, i've tried but it didn't work. 

```
@JsonRootName("info")
static class Info {

		public Info(String name, String sex) {
			super();
			this.name = name;
			this.sex = sex;
		}

		private String name;

		private String sex;

                 ...
		setters and getters
                 ...

	}
```

**Comment by cowtowncoder** [comment]
Behavior of JSON and XML differ because they are conceptually different data formats: they cannot be handled identically.
I don't just mean curly braces vs angle brackets, but rather that structural components are different.

Because of this certain wrapping that XML typically requires (since it lacks native Array type, elements are used for Arrays and Objects) are not added in JSON.

So I don't think there is anything to work on here.

If you have specific types of JSON or XML structures you want, please file issue at appropriate repo (for XML, this one, for JSON jackson-databind). But general "why isn't JSON output like XML" (and vice versa) questions are not useful.
