### ISSUE TITLE
XmlMapper instantiation fails on branch 2.16 due to databind #4101

### ISSUE THREAD

**Issue by k163377** [FasterXML/jackson-dataformat-xml#607]
This is a transcription of an issue reported on the jackson-dev mailing list.

---

The cause is that the following PR added a null check for cache.
https://github.com/FasterXML/jackson-databind/pull/4101/files#diff-25c6303c76a7f05a72cdc35a1271bcc9374db3745d61ab895e7199f050619f7eR168

XmlMapper passes null to the cache, which causes an error.
https://github.com/FasterXML/jackson-dataformat-xml/blame/d1766c9fc014d95b99657b00a0b52e610bd75004/src/main/java/com/fasterxml/jackson/dataformat/xml/deser/XmlDeserializationContext.java#L34

**Comment by cowtowncoder** [comment]
Thank for reporting this -- I will see if I can reproduce the problem.

**Comment by cowtowncoder** [comment]
Yes, actually have a compilation incompatibility too. Will resolve.

**Comment by cowtowncoder** [comment]
Note: this does mean that `jackson-dataformat-xml` and `jackson-databind` both need to be 2.16; there is somewhat close coupling due to requirements to keep `DefaultDeserializationContext` compatible (wrt new `withCaches(CacheProvider)`), not way around that.
It does not change Jackson project's official stance anyway (all Jackson components SHOULD have same minor version; no other guarantees given), but is against ideal case (wherein "adjacent" minor versions in dependency direction SHOULD work -- xml-format 2.15 should work with databind 2.16 -- but that is not maintained here, due to it not being possible, basically).
